[package]
name = "lumber"
version = "0.1.0"
authors = ["Cameron Eldridge <cameldridge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paw = "1.0"
pest = "2.1"
pest_derive = "2.1"
ramp = "0.5"
structopt = { version = "0.3", features = ["paw"] }
weak-table = "0.3"
